### ISSUE TITLE
Currency conversion for price min/max

### ISSUE THREAD

**Issue by blam6** [BoPeng/ai-marketplace-monitor#122]
When I have a search item across multiple countries is it possible to have the price min/max value in base USD automatically converted to their equivalent in the other countries’ currencies?

If not I’d like that feature so that I wouldn’t have to define additional search items & their equivalent currency price min/max for each country.

**Comment by BoPeng** [comment]
Thanks for the feature request!

I'm not entirely sure how this can be best implemented. Facebook accepts min/max prices via a form and infers the currency based on the region where the search is performed, so you do need to provide different min/max values when you search across regions.

To support this feature properly in ai-marketplace-monitor, we would need to manage three pieces of information:

1. The currency used for the min/max price (e.g., allowing inputs like `$10`).
2. The default currency associated with each search city or region.
3. A conversion table to map min/max prices to the appropriate local currency.

Since accurate currency conversion isn’t critical for this use case—and full multi-currency support adds complexity—we could complete something simple:

1. Assume all min/max prices are in a default currency 
2. Introduce an optional parameter to adjust for regional conversion, without explicitly specifying the target currency.

For example:

```toml
[item]
min_price = 100
search_city = 'xxx'
currency_conversion_rate = 105
```

Or, for multiple cities:

```toml
[item]
min_price = 100
search_city = ['xxx', 'yyy']
currency_conversion_rate = [105, 1]
```

A more structured format using regions might look like:

```toml
[item]
min_price = 100
search_region = ['xxx', 'yyy']

[region_xxx]
search_city = ['city1', 'city2']
currency_conversion_rate = 105

[region_yyy]
search_city = ['city3', 'city4']
currency_conversion_rate = 1
```

However, this approach may introduce confusion—users might expect the search to use the local currency, and silently applying conversion rates could lead to unexpected results. Because of this, I'm not fully convinced this is the best solution, but it might be a starting point for further discussion.

**Comment by blam6** [comment]
Thanks for the quick reply Bo. I will chew on that and get back to you. In the meantime - I was wanting to donate, support the project and get some personalised private support. How do I reach you? I tried a link on PyPi but the PayPal donation link was broken. Thanks

**Comment by bo-unitysvc** [comment]
I just tried and the donation link https://www.paypal.com/donate/?hosted_button_id=3WT5JPQ2793BN works. What exactly do you mean by not working? Could you try again? It is possible that this link does not accept oversea donation if you are not from the US though.

**Comment by blam6** [comment]
Yes it doesn’t work, I get “Donations to this recipient aren’t supported in this country”.

I can do Wise, or I could try the GItHub “sponsor" option?

**Comment by bo-unitysvc** [comment]
I see. You could try the github sponsor option.

**Comment by BoPeng** [comment]
I see. You could try the github sponsor option.

**Comment by BoPeng** [comment]
A better implementation is to specify the currency of the city for which the item is searched. For example

```toml
[item]
min_price = '100 GBN'
search_city = ['xxx', 'yyy']
currency = ['GBN', 'EUR']
```

```toml
[item]
min_price = '100 USD'
search_region = ['xxx', 'yyy']

[region_xxx]
search_city = ['city1', 'city2']
currency = 'GBN'

[region_yyy]
search_city = ['city3', 'city4']
currency = 'EUR'
```

Then, `min/max` price will be adjusted according to conversion rate reported by [currencyconverter](https://github.com/alexprengere/currencyconverter/tree/master).

Backward compatibility will be ensured when the conversion only happens whn currency for both `min/max` price and `search_city` are provided.
